export const NOTIFICATION_TYPES = {
  SPONSOR_OR_GODCHILD_CREATE_DONATION: 'SPONSOR_OR_GODCHILD_CREATE_DONATION',
  SOMEONE_ADD_POLL_ANSWER_TO_YOUR_DONATION: 'SOMEONE_ADD_POLL_ANSWER_TO_YOUR_DONATION',
  SOMEONE_UPDATE_POLL_ANSWER_TO_YOUR_DONATION: 'SOMEONE_UPDATE_POLL_ANSWER_TO_YOUR_DONATION',
  SOMEONE_ADD_COMMENT_TO_YOUR_DONATION: 'SOMEONE_ADD_COMMENT_TO_YOUR_DONATION',
  SOMEONE_QUIT_YOUR_DONATION: 'SOMEONE_QUIT_YOUR_DONATION',
  CLOSE_POLL_TO_YOUR_CURRENT_DONATION: 'CLOSE_POLL_TO_YOUR_CURRENT_DONATION',
  FINAL_DATE_TO_YOUR_CURRENT_DONATION: 'FINAL_DATE_TO_YOUR_CURRENT_DONATION',
  DONATION_DONE: 'DONATION_DONE',
  DONATION_STATISTICS: 'DONATION_STATISTICS',
  ELIGIBLE_TO_NEW_DONATION: 'ELIGIBLE_TO_NEW_DONATION',
  FIRST_DONATION_REMINDER: 'FIRST_DONATION_REMINDER',
};

export class Notification {
  constructor({ type, date, donationId, author, data }) {
    this.type = type;
    this.date = date;
    this.donationId = donationId;
    this.author = author;
    this.data = data;
  }
}
