# Remove all containers : docker rm $(docker ps -a -q)
# Remove all images : docker rmi $(docker images -q)

version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodb:/data/db
      - ./conf/docker:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: katellea
      MONGODB_USERNAME: katellea
      MONGODB_PASSWORD: katellea_pwd


  mongo-test:
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - ./conf/docker:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: katellea-test
      MONGODB_USERNAME: katellea
      MONGODB_PASSWORD: katellea_pwd


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081