# Remove all containers : docker rm $(docker ps -a -q)
# Remove all images : docker rmi $(docker images -q)

version: '3.1'

services:

  # https://github.com/bitnami/bitnami-docker-mongodb
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - ./docker/mongodb:/bitnami/mongodb
    ports:
      - '27017:27017'
    user: 'root'
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: katellea
      MONGODB_PASSWORD: katellea_pwd
      MONGODB_DATABASE: katellea

  mongo-test:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_DATABASE: katellea-test
      MONGODB_USERNAME: katellea
      MONGODB_PASSWORD: katellea_pwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081